on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Read Go version
        id: go-version
        run: echo "::set-output name=version::$(cat ./.go-version)"
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run go vet
        run: make vet
      - name: Install vault, nomad, consul
        env:
          NOMAD_LICENSE: ${{ secrets.NOMAD_LICENSE }}
        run: |
          ./scripts/getnomad.sh
          ./scripts/getvault.sh
          ./scripts/getconsul.sh
      - name: Start nomad
        env:
          NOMAD_LICENSE: ${{ secrets.NOMAD_LICENSE }}
        run: ./scripts/start-nomad.sh
      - name: Run acceptance tests
        run: NOMAD_TOKEN=${{ env.NOMAD_TOKEN }} make testacc
      - name: Make Nomad data dir and log file readable
        if: always()
        run: |
          sudo chmod -R 777 /tmp/nomad
          sudo chmod 666 /tmp/nomad.log
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: |
            /tmp/consul.log
            /tmp/nomad.log
            /tmp/vault.log
            /tmp/nomad/data/**/alloc/logs/plugin*
            !/tmp/nomad/data/**/alloc/logs/*.fifo
          if-no-files-found: warn
          retention-days: 3
      - name: Stop nomad
        run: ./scripts/stop-nomad.sh
